version: "3"
services:
  bandersnatch_db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: bandersnatch
      POSTGRES_USER: postgres
      POSTGRES_DB: bandersnatch
    ports:
      - "5432:5432"
    networks:
      - "service"
    volumes:
      - ./data:/var/lib/postgresql/
networks:
  service:
